/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  corePlugins: {
    preflight: true,
  },
  theme: {
    extend: {
      colors: {
        venmo: {
          blue: {
            50: 'var(--color-venmo-blue-50)',
            100: 'var(--color-venmo-blue-100)',
            200: 'var(--color-venmo-blue-200)',
            300: 'var(--color-venmo-blue-300)',
            400: 'var(--color-venmo-blue-400)',
            500: 'var(--color-venmo-blue-500)',
            600: 'var(--color-venmo-blue-600)',
            700: 'var(--color-venmo-blue-700)',
            800: 'var(--color-venmo-blue-800)',
            900: 'var(--color-venmo-blue-900)',
            DEFAULT: 'var(--color-venmo-blue)',
          },
          purple: {
            50: 'var(--color-venmo-purple-50)',
            100: 'var(--color-venmo-purple-100)',
            200: 'var(--color-venmo-purple-200)',
            300: 'var(--color-venmo-purple-300)',
            400: 'var(--color-venmo-purple-400)',
            500: 'var(--color-venmo-purple-500)',
            600: 'var(--color-venmo-purple-600)',
            700: 'var(--color-venmo-purple-700)',
            800: 'var(--color-venmo-purple-800)',
            900: 'var(--color-venmo-purple-900)',
            DEFAULT: 'var(--color-venmo-purple)',
          },
        },
        'deep-blue': 'var(--color-deep-blue)',
        background: 'var(--color-background)',
        'card-white': 'var(--color-card-white)',
        'border-gray': 'var(--color-border-gray)',
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
        },
        success: {
          light: 'var(--color-success-light)',
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
        },
        warning: {
          light: 'var(--color-warning-light)',
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
        },
        error: {
          light: 'var(--color-error-light)',
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
        },
        info: {
          light: 'var(--color-info-light)',
          DEFAULT: 'var(--color-info)',
          dark: 'var(--color-info-dark)',
        },
      },
      spacing: {
        0: 'var(--spacing-0)',
        1: 'var(--spacing-1)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        8: 'var(--spacing-8)',
        10: 'var(--spacing-10)',
        12: 'var(--spacing-12)',
        16: 'var(--spacing-16)',
        20: 'var(--spacing-20)',
        24: 'var(--spacing-24)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        none: 'var(--shadow-none)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        focus: 'var(--shadow-focus)',
      },
      fontFamily: {
        sans: 'var(--font-family-base)',
      },
      fontSize: {
        'display-lg': 'var(--font-size-display-lg)',
        'display': 'var(--font-size-display)',
        'h1': 'var(--font-size-h1)',
        'h2': 'var(--font-size-h2)',
        'h3': 'var(--font-size-h3)',
        'body-lg': 'var(--font-size-body-lg)',
        'body': 'var(--font-size-body)',
        'body-sm': 'var(--font-size-body-sm)',
        'caption': 'var(--font-size-caption)',
      },
      fontWeight: {
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      lineHeight: {
        tight: 'var(--line-height-tight)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
      },
      letterSpacing: {
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        medium: 'var(--duration-medium)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'in-out': 'var(--ease-in-out)',
        'out': 'var(--ease-out)',
        'in': 'var(--ease-in)',
        'bounce': 'var(--ease-bounce)',
      },
      zIndex: {
        base: 'var(--z-index-base)',
        dropdown: 'var(--z-index-dropdown)',
        sticky: 'var(--z-index-sticky)',
        fixed: 'var(--z-index-fixed)',
        'modal-backdrop': 'var(--z-index-modal-backdrop)',
        modal: 'var(--z-index-modal)',
        popover: 'var(--z-index-popover)',
        tooltip: 'var(--z-index-tooltip)',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-success': 'var(--gradient-success)',
        'gradient-error': 'var(--gradient-error)',
      },
    },
    screens: {
      mobile: { max: '767px' },
      tablet: { min: '768px', max: '1023px' },
      desktop: { min: '1024px' },
      'lg-desktop': { min: '1440px' },
    },
  },
  plugins: [],
}

