import { Pool } from 'pg';

/**
 * InvoiceNumber Value Object
 * Format: INV-{sequence} where sequence is from invoice_number_seq
 * Example: INV-1000, INV-1001, etc.
 */
export class InvoiceNumber {
  // Special constant for pending invoice numbers (to be generated by DB)
  static readonly PENDING = '';

  constructor(public readonly value: string) {
    // Allow empty string as a pending value (will be generated by DB)
    if (value !== InvoiceNumber.PENDING && !InvoiceNumber.isValid(value)) {
      throw new Error('INVALID_INVOICE_NUMBER_FORMAT');
    }
  }

  /**
   * Validate invoice number format
   */
  static isValid(value: string): boolean {
    return /^INV-\d+$/.test(value);
  }
  
  /**
   * Check if this is a pending invoice number (not yet generated)
   */
  isPending(): boolean {
    return this.value === InvoiceNumber.PENDING;
  }

  /**
   * Generate a new invoice number using the database sequence
   */
  static async generate(pool: Pool): Promise<InvoiceNumber> {
    const result = await pool.query("SELECT nextval('invoice_number_seq') as sequence");
    const sequence = result.rows[0].sequence;
    return new InvoiceNumber(`INV-${sequence}`);
  }

  toString(): string {
    return this.value;
  }

  toJSON(): string {
    return this.value;
  }
}

